import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <nav className="bg-white shadow p-4 flex gap-6">
          <Link href="/portal">Portal</Link>
          <Link href="/recarga">Recarga</Link>
          <Link href="/paquetes">Paquetes</Link>
          <Link href="/tienda">Tienda</Link>
          <Link href="/cuenta">Cuenta</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
